### ISSUE TITLE
Await errors

### ISSUE THREAD

**Issue by KriperProject** [fsommer95/Kademlia-Chat#1]
I'm trying to launch the chat program but It returns this errors:

chat.py:67: RuntimeWarning: coroutine 'Server.listen' was never awaited   node.listen(5678)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "chat.py", line 72, in <module>
    loop.run_until_complete(node.bootstrap([("1.1.1.1", 8468)]))
  File "C:\Users\Juanix\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Juanix\AppData\Roaming\Python\Python38\site-packages\kademlia\network.py", line 126, in bootstrap
    gathered = await asyncio.gather(*cos)
  File "C:\Users\Juanix\AppData\Roaming\Python\Python38\site-packages\kademlia\network.py", line 133, in bootstrap_node
    result = await self.protocol.ping(addr, self.node.id)
AttributeError: 'NoneType' object has no attribute 'ping'

Process finished with exit code 1

Any idea?

Thanks a lot

**Comment by KriperProject** [comment]
Fixed.
